=begin
#React With Vite Rails API

#react_with_vite_rails リポジトリのAPIスキーマです

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::FruitsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::FruitsResponse do
  let(:instance) { OpenapiClient::FruitsResponse.new }

  describe 'test an instance of FruitsResponse' do
    it 'should create an instance of FruitsResponse' do
      expect(instance).to be_instance_of(OpenapiClient::FruitsResponse)
    end
  end
  describe 'test attribute "fruits"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
