=begin
#React With Vite Rails API

#react_with_vite_rails リポジトリのAPIスキーマです

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ArrayInQueryParamsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ArrayInQueryParamsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ArrayInQueryParamsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArrayInQueryParamsApi' do
    it 'should create an instance of ArrayInQueryParamsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ArrayInQueryParamsApi)
    end
  end

  # unit tests for fetch_array_in_query_params_fruits
  # Arrayをクエリ文字列に入れてリクエストするAPI 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :names 果物の名前のリスト 
  # @return [FruitsResponse]
  describe 'fetch_array_in_query_params_fruits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
