=begin
#React With Vite Rails API

#react_with_vite_rails リポジトリのAPIスキーマです

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

module OpenapiClient
  VERSION = '1.0.0'
end
